//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapayaX2.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class rs_assets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rs_assets()
        {
            this.rs_accessories = new HashSet<rs_accessories>();
            this.rs_assets_rel = new HashSet<rs_assets_rel>();
            this.rs_assets_rel1 = new HashSet<rs_assets_rel>();
            this.rs_bookings = new HashSet<rs_bookings>();
            this.rs_bookstats = new HashSet<rs_bookstats>();
        }
    
        public int AssetId { get; set; }
        public int ParentId { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string Desciption { get; set; }
        public string SerialNumber { get; set; }
        public string MaterialNo { get; set; }
        public string HardwareOpt { get; set; }
        public string SoftwareOpt { get; set; }
        public string HardwareVer { get; set; }
        public string SoftwareVer { get; set; }
        public Nullable<System.DateTime> LicenseExpiry { get; set; }
        public string Accessories { get; set; }
        public string Remarks { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<System.DateTime> DecomDate { get; set; }
        public string DecomReason { get; set; }
        public bool Tagged { get; set; }
        public bool Damaged { get; set; }
        public Nullable<System.DateTime> LastCalibrated { get; set; }
        public Nullable<int> CalibrationCycle { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int CreatedBy { get; set; }
        public int OwnerShipId { get; set; }
        public int OwnedBy { get; set; }
        public string TrackingNo { get; set; }
        public bool ReadyToSell { get; set; }
        public int Availability { get; set; }
        public int OriginLocId { get; set; }
        public int CurrentLocId { get; set; }
        public string PurchasePO { get; set; }
        public string DepreciationFormula { get; set; }
        public string ImageLink { get; set; }
        public long ViewedStats { get; set; }
        public long BookingStats { get; set; }
        public int FeaturedOrder { get; set; }
        public bool Featured { get; set; }
        public bool IsSystem { get; set; }
        public int DivId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rs_accessories> rs_accessories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rs_assets_rel> rs_assets_rel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rs_assets_rel> rs_assets_rel1 { get; set; }
        public virtual rs_assets rs_assets1 { get; set; }
        public virtual rs_assets rs_assets2 { get; set; }
        public virtual rs_division rs_division { get; set; }
        public virtual rs_ownership rs_ownership { get; set; }
        public virtual rs_user rs_user { get; set; }
        public virtual rs_locations rs_locations { get; set; }
        public virtual rs_locations rs_locations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rs_bookings> rs_bookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rs_bookstats> rs_bookstats { get; set; }
    }
}
