//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapayaX2.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class rs_bookings
    {
        public int BookId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<System.DateTime> ExtendedDate { get; set; }
        public bool Extended { get; set; }
        public bool Approved { get; set; }
        public System.DateTime BookAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public int ResquestorId { get; set; }
        public int CreatedBy { get; set; }
        public int ApproverId { get; set; }
        public int AssetId { get; set; }
        public string Remarks { get; set; }
        public string Purpose { get; set; }
        public bool Returned { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<int> LoanLocationId { get; set; }
        public int ReturnLocationId { get; set; }
        public bool Damaged { get; set; }
        public Nullable<int> LoanFormId { get; set; }
        public int VerifyBy { get; set; }
        public string ReturnRemark { get; set; }
        public Nullable<int> ReturnBy { get; set; }
    
        public virtual rs_assets rs_assets { get; set; }
        public virtual rs_locations rs_locations { get; set; }
        public virtual rs_user rs_user { get; set; }
        public virtual rs_loan_form rs_loan_form { get; set; }
        public virtual rs_user rs_user1 { get; set; }
        public virtual rs_user rs_user2 { get; set; }
        public virtual rs_user rs_user3 { get; set; }
        public virtual rs_user rs_user4 { get; set; }
    }
}
