//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapayaX2.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class rs_syslog
    {
        public long LogId { get; set; }
        public string ClientIP { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string Operation { get; set; }
        public string Description { get; set; }
        public string User { get; set; }
        public Nullable<System.DateTime> LogTime { get; set; }
    }
}
