//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapayaX2.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class rs_smslogs
    {
        public int MessageId { get; set; }
        public int ReceiverId { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Action { get; set; }
        public string Message { get; set; }
    
        public virtual rs_user rs_user { get; set; }
    }
}
