//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapayaX2.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class rs_useracl
    {
        public int UserAclId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> ActionId { get; set; }
        public bool FlagActive { get; set; }
        public string UserEntry { get; set; }
        public Nullable<System.DateTime> DateEntry { get; set; }
        public string UserUpdate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
    
        public virtual rs_action rs_action { get; set; }
        public virtual rs_user_group rs_user_group { get; set; }
    }
}
