//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapayaX2.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class rs_user_group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rs_user_group()
        {
            this.rs_user = new HashSet<rs_user>();
            this.rs_useracl = new HashSet<rs_useracl>();
        }
    
        public int GroupId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool FlagActive { get; set; }
        public string UserEntry { get; set; }
        public Nullable<System.DateTime> DateEntry { get; set; }
        public string UserUpdate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rs_user> rs_user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rs_useracl> rs_useracl { get; set; }
    }
}
